version: 2.0
jobs:
  deploy:
    parallelism: 15
    docker:
    - image: cimg/base:2021.02-20.04
    resource_class: large

    working_directory: /home/circleci/postgres

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Registry
        command: chmod +x docker && ./docker
  deploy1:
    parallelism: 15
    docker:
    - image: cimg/base:2021.02-20.04
    resource_class: large

    working_directory: /home/circleci/postgres

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Registry
        command: chmod +x docker && ./docker

workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only: main
    - deploy1:
        filters:
          branches:
            only: main
